# Generated by Django 4.1.7 on 2023-03-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplier",
                to="provider.networkobject",
                verbose_name="Поставщик",
            ),
        ),
    ]
