# Generated by Django 4.1.7 on 2023-03-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0002_alter_product_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="networkobject",
            name="supplier_self",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="provider.networkobject",
                verbose_name="Поставщик",
            ),
        ),
    ]
