# Generated by Django 4.1.7 on 2023-03-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0003_networkobject_supplier_self"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="networkobject",
            name="supplier_self",
        ),
    ]
