# Generated by Django 4.1.7 on 2023-03-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("provider", "0004_remove_networkobject_supplier_self"),
    ]

    operations = [
        migrations.RenameField(
            model_name="individualentrepreneur",
            old_name="retail_network",
            new_name="supplier",
        ),
        migrations.RenameField(
            model_name="retailnetwork",
            old_name="retail_factory",
            new_name="supplier",
        ),
        migrations.AlterField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="provider.networkobject",
                verbose_name="Поставщик",
            ),
        ),
    ]
